version: '3.9'

services:
  nestapp:
    container_name: nestapp
#    image: francescoxx/nestapp:1.0.0
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=secret
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=sboard
      - PG_PORT=5432
      - FRONTEND_URL=${FRONTEND_URL}
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sboard
    volumes:
      - pgdata:/var/lib/postgresql14/data
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=${PGADMIN_CONFIG_SERVER_MODE}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    depends_on:
      - db
volumes:
  pgadmin-data: {}
  pgdata: {}